import {anniversaryPromos,supplementPromos} from './promo-catalog.ts';
import {tcg} from './data.ts';
import {nameScore,rankNames,parseNumber,parseCardQuery,matchesQuery} from './search.ts';
const cache=new Map<string,{expires:number,data:any}>();
export async function catalog(path:string,lang:string):Promise<any>{if(path==='sets/30th-promos'){const parent=await catalog('sets/mep',lang);return {...parent,id:'30th-promos',name:lang==='de'?'30 Jahre · Jubiläums-Promos':'30th Celebration · Anniversary Promos',cards:parent.cards.filter((c:any)=>/^mep-(094|095|096|097|098|099|10[0-9]|110)$/.test(c.id)),cardCount:{official:0,total:17}};}const key=lang+'/'+path,hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit.data;let data:any;try{data=await tcg(path,lang);}catch(e){const n=path.match(/^cards\/mep-(\d{3})$/)?.[1];if(lang!=='de'||!n||!anniversaryPromos[n])throw e;data=await tcg(path,'en');data={...data,name:anniversaryPromos[n],imageLanguage:'en',catalogSupplement:true,promoGroup:'30 Jahre'};}if(path==='sets'&&!data.some((s:any)=>s.id==='30th-promos'))data=[...data,{id:'30th-promos',name:lang==='de'?'30 Jahre · Jubiläums-Promos':'30th Celebration · Anniversary Promos',cardCount:{official:0,total:17},releaseDate:'2026-09-16'}];const promoNum=path.match(/^cards\/mep-(\d{3})$/)?.[1];if(lang==='de'&&promoNum&&anniversaryPromos[promoNum])data={...data,name:anniversaryPromos[promoNum],promoGroup:'30 Jahre'};if(lang==='de'&&path==='cards')data=supplementPromos(data,lang);if(lang==='de'&&path==='sets/mep')data={...data,cards:supplementPromos(data.cards,lang,true)};if(cache.size>1000)cache.clear();cache.set(key,{data,expires:Date.now()+600000});return data;}
export const physical=(c:any)=>!/^[A-Z]\d|^P-A/.test(c.id);
export const promo=(s:any)=>/promo/i.test(s.name)||['basep','dpp','hgssp','bwp','xyp','smp','swshp','svp','mep'].includes(s.id);
export {parseNumber} from './search.ts';
export function matches(c:any,q:string){return matchesQuery(c,parseCardQuery(q));}
async function setInfo(rows:any[],lang:string,total:string){const ids=[...new Set(rows.map(c=>c.id.slice(0,c.id.lastIndexOf('-'))))],info=new Map<string,any>();let cursor=0;const worker=async()=>{while(cursor<ids.length){const id=ids[cursor++];try{info.set(id,await catalog('sets/'+id,lang));}catch{}}};await Promise.all(Array.from({length:Math.min(6,ids.length)},worker));return rows.flatMap(c=>{const set=info.get(c.id.slice(0,c.id.lastIndexOf('-')));if(total&&/^\d+$/.test(total)&&Number(set?.cardCount?.official)!==Number(total))return [];return [{...c,setName:set?.name||c.setName,set:set?{id:set.id,name:set.name,cardCount:set.cardCount}:c.set}];});}
export async function searchCards(q:string,lang:string,setId:string,onlyPromo:boolean){const parsed=parseCardQuery(q);setId=setId||parsed.set;let rows:any[];if(setId){const s=await catalog('sets/'+setId,lang);rows=s.cards.map((c:any)=>({...c,setName:s.name,set:{id:s.id,name:s.name,cardCount:s.cardCount}})).filter((c:any)=>matchesQuery(c,parsed));}else if(onlyPromo){const sets=(await catalog('sets',lang)).filter((s:any)=>physical(s)&&promo(s)).reverse();rows=[];for(let i=0;i<sets.length;i+=4){const batches=await Promise.all(sets.slice(i,i+4).map(async(s:any)=>{const detail=await catalog('sets/'+s.id,lang);return detail.cards.map((c:any)=>({...c,setName:detail.name,set:{id:detail.id,name:detail.name,cardCount:detail.cardCount}})).filter((c:any)=>matchesQuery(c,parsed));}));rows.push(...batches.flat());}}else rows=[...await catalog('cards',lang)].reverse().filter((c:any)=>matchesQuery(c,parsed));rows=[...new Map(rows.filter(physical).map(c=>[c.id,c])).values()];if(parsed.name)rows=rankNames(rows,parsed.name,(c:any)=>c.name);if(parsed.total)rows=await setInfo(rows,lang,parsed.total);else rows=await setInfo(rows.slice(0,60),lang,'');return rows.slice(0,60);}
export async function alternateImage(id:string,lang:string){const alternate=lang==='en'?'de':'en';try{const c=await catalog('cards/'+id,alternate);return {image:c.image||null,language:alternate};}catch{return {image:null};}}

export async function scanCards(number:string,name:string,lang:string,setId:string){const query=[name,number].filter(Boolean).join(' ');return searchCards(query,lang,setId,false);}
