import {sealedRows} from './sealed.ts';
import {db} from './data.ts';
import {withPhotos} from './photos.ts';
import {attachImage} from './verified-images.ts';
import {quote} from './pricing.ts';
import {gradedValue} from './grading.ts';
export async function members(){return (await db().prepare('SELECT user_id, username, role, active FROM portal_accounts').all()).results.filter((a:any)=>a.user_id&&a.active!==false);}
function sharedData(r:any){const data=JSON.parse(r.data);if(data.personalMarketQuote){delete data.cardPriceHistory;delete data.cardPriceHistoriesByVariant;}delete data.personalMarketQuote;return data;}
function cents(r:any){const data=sharedData(r),price=r.grading?gradedValue(data,r.grading):quote(data,r.variant).price;return r.manual_cents!==null?r.manual_cents:price===null?null:Math.round(price*100);}
export async function directory(search:string,page:number){const d=db(),accounts=(await members()).filter((a:any)=>a.username.toLowerCase().includes(search.toLowerCase())).sort((a:any,b:any)=>a.username.localeCompare(b.username));const start=page*24;const collectors=await Promise.all(accounts.slice(start,start+24).map(async(a:any)=>{const [cards,collections]=await Promise.all([d.prepare('SELECT * FROM cards WHERE owner = ?').bind(a.user_id).all(),d.prepare('SELECT id FROM collections WHERE owner = ?').bind(a.user_id).all()]);let totalCents=0,count=0,unpriced=0;for(const r of cards.results){const value=cents(r);count+=r.quantity;if(value===null)unpriced+=r.quantity;else totalCents+=value*r.quantity;}const sealed=await sealedRows(a.user_id,true);return {username:a.username,totalCents,count,unpriced,collectionCount:collections.results.length,sealedCount:sealed.reduce((n:number,r:any)=>n+r.quantity,0),sealedValueCents:sealed.reduce((n:number,r:any)=>n+(r.value_cents||0)*r.quantity,0)};}));return {collectors,total:accounts.length,page,pageSize:24};}
export async function collector(username:string){const account=(await members()).find((a:any)=>a.username===username);if(!account)return null;const d=db();const [collections,cards]=await Promise.all([d.prepare('SELECT * FROM collections WHERE owner = ? ORDER BY created').bind(account.user_id).all(),d.prepare('SELECT * FROM cards WHERE owner = ? ORDER BY fetched DESC').bind(account.user_id).all()]);return {username:account.username,sealedItems:await sealedRows(account.user_id,true),collections:collections.results.map((c:any)=>({id:c.id,name:c.name,kind:c.kind||'cards'})),cards:(await withPhotos(cards.results)).map((r:any)=>{const data=sharedData(r),market=quote(data,r.variant);return {id:r.id,collection_id:r.collection_id,quantity:r.quantity,language:r.language,variant:r.variant,condition:r.condition,grading:r.grading,data:attachImage({...data,customImageUrl:r.customImageUrl,customPhotoId:r.customPhotoId,customImageShared:r.customImageShared},r.language),valueCents:cents(r),valueSource:r.manual_cents!==null?'Eigener Wert':r.grading?gradedValue(data,r.grading)===null?'Grading: Wert offen':data.gradedQuote.estimated||data.gradedQuote.comparison?'Schätzwert · '+data.gradedQuote.reference:'Verkaufsmedian · '+data.gradedQuote.reference:(market.manualApproved?'Cardmarket-Angebot · manuell geprüft · '+r.language.toUpperCase():market.scope==='language'?'Cardmarket-Angebot · '+r.language.toUpperCase():'Cardmarket-Trend · sprachübergreifend'),priceDate:r.grading?data.gradedQuote?.sourceUpdated||data.gradedQuote?.fetchedAt||null:market.updated};})};}
