import {createAccount} from './accounts.ts';
import {GET,POST} from './api.ts';
import {auth} from './auth.ts';
import {db,isAdmin} from './data.ts';
import {refresh,today} from './history.ts';
declare const Deno:{serve(handler:(request:Request)=>Promise<Response>):void};
async function daily(){const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',hour:'2-digit',hourCycle:'h23'}).format(new Date()));if(hour<8)return {waiting:true};const day=today(),owners=(await db().prepare('SELECT DISTINCT owner FROM collections').all()).results;for(const {owner} of owners){const job:any=await db().prepare('SELECT * FROM refresh_jobs WHERE owner=?').bind(owner).first();if(job?.day===day&&job.complete)continue;const cursor=job?.day===day?job.cursor:0,failed=job?.day===day?job.failed:0;const result=await refresh(owner,cursor,failed);await db().prepare('INSERT INTO refresh_jobs (owner,day,cursor,failed,complete) VALUES (?,?,?,?,?) ON CONFLICT(owner) DO UPDATE SET day=excluded.day,cursor=excluded.cursor,failed=excluded.failed,complete=excluded.complete').bind(owner,day,result.nextCursor||0,failed+result.failed,result.nextCursor===null?1:0).run();return result;}await db().prepare('DELETE FROM login_attempts WHERE window < ?').bind(Math.floor(Date.now()/600000)-6).run();return {ok:true};}
export async function handle(request:Request){try{const u=new URL(request.url);const path=u.pathname.replace(/^\/pokevault|^\/functions\/v1\/pokevault/,'');let r:Response;if(path==='/api/account'){if(!(await isAdmin(request)))return Response.json({error:'Nicht erlaubt.'},{status:401});if(request.method!=='POST')return Response.json({error:'Methode nicht erlaubt.'},{status:405});r=await createAccount(request);}else if(path==='/api/daily'){if(!(await isAdmin(request)))return Response.json({error:'Nicht erlaubt.'},{status:401});if(request.method!=='POST')return Response.json({error:'Methode nicht erlaubt.'},{status:405});r=Response.json(await daily());}else if(['/api/auth','/api/auth/refresh','/api/auth/logout','/api/auth/recover','/api/auth/reset'].includes(path)){r=await auth(request);}else if(path==='/api/vault'){r=request.method==='GET'?await GET(request):request.method==='POST'?await POST(request):Response.json({error:'Methode nicht erlaubt.'},{status:405});}else r=Response.json({error:'Nicht gefunden.'},{status:404});const h=new Headers(r.headers);h.set('Cache-Control','no-store');h.set('X-Content-Type-Options','nosniff');return new Response(r.body,{status:r.status,headers:h});}catch{console.error('Portal request failed');return Response.json({error:'Der Dienst ist momentan nicht verfügbar.'},{status:503});}}
Deno.serve(handle);
