// English glosses of the Japanese set titles, keyed by the original printing code.
// These identify Japanese products; they are not English counterpart expansions.
// Japanese catalogue: https://github.com/tcgdex/cards-database/tree/master/data-asia
export const japaneseSetEnglish:Record<string,string>={
  "PMCG1": "Expansion Pack",
  "PMCG2": "Pokémon Jungle",
  "PMCG3": "Mystery of the Fossils",
  "PMCG4": "Rocket Gang",
  "PMCG5": "Leaders' Stadium",
  "PMCG6": "Challenge from the Darkness",
  "neo1": "Gold, Silver, to a New World...",
  "neo2": "Crossing the Ruins...",
  "neo3": "Awakening Legends",
  "neo4": "Darkness, and to Light...",
  "VS1": "Pokémon Card VS",
  "web1": "Pokémon Card web",
  "E1": "Base Expansion Pack",
  "E2": "The Town on No Map",
  "E3": "Wind from the Sea",
  "E4": "Split Earth",
  "E5": "Mysterious Mountains",
  "ADV1": "ADV Expansion Pack",
  "ADV2": "Miracle of the Desert",
  "ADV3": "Rulers of the Heavens",
  "ADV4": "Magma VS Aqua: Two Ambitions",
  "ADV5": "Undone Seal",
  "PCG1": "Flight of Legends",
  "PCG2": "Clash of the Blue Sky",
  "PCG3": "Rocket Gang Strikes Back",
  "PCG4": "Golden Sky, Silvery Ocean",
  "PCG5": "Mirage Forest",
  "PCG6": "Holon Research Tower",
  "PCG7": "Holon Phantom",
  "PCG8": "Miracle Crystal",
  "PCG9": "Offense and Defense of the Furthest Ends",
  "PCG10": "World Champions Pack",
  "L1b": "SoulSilver Collection",
  "L1a": "HeartGold Collection",
  "L2": "Reviving Legends",
  "LL": "Lost Link",
  "L3": "Clash at the Summit",
  "XY1b": "Collection Y",
  "XY1a": "Collection X",
  "XY2": "Wild Blaze",
  "XY3": "Rising Fist",
  "XY4": "Phantom Gate",
  "XY5a": "Gaia Volcano",
  "XY5b": "Tidal Storm",
  "CP1": "Magma Gang VS Aqua Gang: Double Crisis",
  "XY6": "Emerald Break",
  "XY7": "Bandit Ring",
  "CP2": "Legendary Shine Collection",
  "XY8a": "Blue Shock",
  "XY8b": "Red Flash",
  "XY9": "Rage of the Broken Heavens",
  "CP3": "PokéKyun Collection",
  "XY10": "Awakening Psychic King",
  "CP4": "Premium Champion Pack EX × M × BREAK",
  "XY11b": "Cruel Traitor",
  "XY11a": "Fever-Burst Fighter",
  "CP5": "Mythical & Legendary Dream Shine Collection",
  "CP6": "Expansion Pack 20th Anniversary",
  "SM0": "Pikachu and New Friends",
  "SM1M": "Collection Moon",
  "SM1S": "Collection Sun",
  "SM1+": "Sun & Moon",
  "SM2L": "Alolan Moonlight",
  "SM2K": "Islands Await You",
  "sm2+": "Facing a New Trial",
  "SM3N": "Darkness that Consumes Light",
  "SM3H": "To Have Seen the Battle Rainbow",
  "SM3+": "Shining Legends",
  "SM4S": "Awakened Heroes",
  "SM4A": "Ultradimensional Beasts",
  "SM4+": "GX Battle Boost",
  "SM5S": "Ultra Sun",
  "SM5M": "Ultra Moon",
  "SM5+": "Ultra Force",
  "SM6": "Forbidden Light",
  "SM6a": "Dragon Storm",
  "SM6b": "Champion Road",
  "SM7": "Sky-Splitting Charisma",
  "SM7b": "Fairy Rise",
  "SM7a": "Thunderclap Spark",
  "SM8": "Super-Burst Impact",
  "SM8a": "Dark Order",
  "SM8b": "GX Ultra Shiny",
  "SM9": "Tag Bolt",
  "SM9a": "Night Unison",
  "SM9b": "Full Metal Wall",
  "SM10": "Double Blaze",
  "SM10a": "GG End",
  "SMP2": "Detective Pikachu",
  "SM10b": "Sky Legend",
  "SM11": "Miracle Twin",
  "SM11a": "Remix Bout",
  "SM11b": "Dream League",
  "SM12": "Alter Genesis",
  "SM12a": "TAG TEAM GX: Tag All Stars",
  "S1W": "Sword",
  "S1H": "Shield",
  "S1a": "VMAX Rising",
  "S2": "Rebellion Crash",
  "S3": "Infinity Zone",
  "S3a": "Legendary Heartbeat",
  "SV7a": "Paradise Dragona",
  "SV5a": "Crimson Haze",
  "SV6a": "Night Wanderer",
  "SV4K": "Ancient Roar",
  "SV4a": "Shiny Treasure ex",
  "SVLN": "Stellar Tera Type Starter Set: Sylveon ex",
  "SV3": "Ruler of the Black Flame",
  "SV2a": "Pokémon Card 151",
  "SV6": "Mask of Change",
  "SV2D": "Clay Burst",
  "SV10": "Glory of Team Rocket",
  "SV11B": "Black Bolt",
  "SV-P": "Scarlet & Violet Promo Cards",
  "SV8": "Super Electric Breaker",
  "SV1a": "Triplet Beat",
  "SV3a": "Raging Surf",
  "SVLS": "Stellar Tera Type Starter Set: Ceruledge ex",
  "SV8a": "Terastal Fest ex",
  "SV5K": "Wild Force",
  "SV9": "Battle Partners",
  "SV4M": "Future Flash",
  "SV1S": "Scarlet ex",
  "SVK": "Stellar Miracle Deck Build Box",
  "SV9a": "Heat Wave Arena",
  "SV2P": "Snow Hazard",
  "SV11W": "White Flare",
  "SV7": "Stellar Miracle",
  "SV5M": "Cyber Judge",
  "SV1V": "Violet ex",
  "S12": "Paradigm Trigger",
  "S7R": "Blue Sky Stream",
  "S7D": "Skyscraping Perfection",
  "S9": "Star Birth",
  "S10D": "Time Gazer",
  "S8a": "25th Anniversary Collection",
  "S5R": "Rapid Strike Master",
  "S5a": "Peerless Fighters",
  "S11": "Lost Abyss",
  "S5I": "Single Strike Master",
  "S11a": "Incandescent Arcana",
  "S6K": "Jet-Black Spirit",
  "S8": "Fusion Arts",
  "S6H": "Silver Lance",
  "S8b": "VMAX Climax",
  "S6a": "Eevee Heroes",
  "S10a": "Dark Phantasma",
  "S10P": "Space Juggler",
  "S4": "Amazing Volt Tackle",
  "S2a": "Explosive Walker",
  "S9a": "Battle Region",
  "S4a": "Shiny Star V",
  "S12a": "VSTAR Universe",
  "S10b": "Pokémon GO",
  "SM5p": "Ultra Force",
  "SM1p": "Sun & Moon",
  "SM4p": "GX Battle Boost",
  "SM3p": "Shining Legends",
  "SM2p": "Facing a New Trial",
  "MC": "Start Deck 100 Battle Collection",
  "M5": "Abyss Eye",
  "M2a": "MEGA Dream ex",
  "M6a": "30th Celebration",
  "MF": "30th Celebration Premium Deck Set: Espeon & Umbreon",
  "M6": "Storm Emerald",
  "M1S": "Mega Symphonia",
  "M2": "Inferno X",
  "M1L": "Mega Brave",
  "M4": "Ninja Spinner",
  "M-P": "Mega Promo Cards",
  "M3": "Nihil Zero (Munikisu Zero)",
  "CS3.5": "Triplet Beat",
  "CS2.5": "Triplet Beat",
  "CS2b": "Triplet Beat",
  "CS4a": "Triplet Beat",
  "CS1.5": "Triplet Beat",
  "CSA": "Triplet Beat",
  "CS3D": "Triplet Beat",
  "CS3a": "Triplet Beat",
  "CS1b": "Triplet Beat",
  "CS2a": "Triplet Beat",
  "CS3b": "Triplet Beat",
  "CS4Da": "Triplet Beat",
  "CS1a": "Triplet Beat",
  "CS4b": "Triplet Beat",
  "CS4": "Triplet Beat"
};
export function englishSetName(set:any){return japaneseSetEnglish[set.id]||set.englishName||'';}

