import {db,env,storage} from './data.ts';
import {catalog,physical} from './catalog.ts';
const bucket='card-photos';
function ownPath(path:string,owner:string){return path.startsWith(owner+'/')&&/^[a-f0-9-]+\.jpg$/.test(path.slice(owner.length+1));}
export async function photoUrl(row:any){if(!row?.photo_path||!ownPath(row.photo_path,row.owner))return null;try{const r=await storage('object/sign/'+bucket+'/'+row.photo_path,{method:'POST',body:JSON.stringify({expiresIn:3600})});return env.SUPABASE_URL+'/storage/v1'+r.signedURL;}catch{return null;}}
export async function catalogPhotos(cards:any[],owner:string,language:string){if(!cards.length)return cards;const images=(await db().prepare('SELECT * FROM card_images WHERE owner = ? AND language = ?').bind(owner,language).all()).results;const byCard=new Map(images.map((i:any)=>[i.card_id,i]));return Promise.all(cards.map(async c=>{const image=byCard.get(c.id);return image?{...c,customImageUrl:await photoUrl(image),customPhotoId:image.id}:c;}));}
export async function withPhotos(rows:any[]){const owners=[...new Set(rows.map(r=>r.owner))];const byCard=new Map<string,any>();for(const owner of owners){const images=(await db().prepare('SELECT * FROM card_images WHERE owner = ?').bind(owner).all()).results;for(const i of images)byCard.set(i.owner+'/'+i.language+'/'+i.card_id,i);}const urls=new Map<string,Promise<string|null>>();const result=[];for(let i=0;i<rows.length;i+=6)result.push(...await Promise.all(rows.slice(i,i+6).map(async r=>{const cardId=r.card_id||JSON.parse(r.data).id,image=byCard.get(r.owner+'/'+r.language+'/'+cardId)||r;const key=image.owner+'/'+image.photo_path;if(!urls.has(key))urls.set(key,photoUrl(image));return {...r,customImageUrl:await urls.get(key),customPhotoId:image.id};})));return result;}
export async function removePhoto(row:any){if(row.photo_path&&ownPath(row.photo_path,row.owner))await storage('object/'+bucket,{method:'DELETE',body:JSON.stringify({prefixes:[row.photo_path]})}).catch(()=>{});}
export async function savePhoto(owner:string,id:string,content:any,cardId?:string,language?:string){const d=db();if(!cardId){const row=await d.prepare('SELECT * FROM cards WHERE id = ? AND owner = ?').bind(id,owner).first();if(!row)throw Error('Bitte eine eigene Karte wählen.');cardId=row.card_id||JSON.parse(row.data).id;language=row.language;}
 if(!cardId||! /^[a-zA-Z0-9.-]{1,100}$/.test(cardId)||!physical({id:cardId})||!['de','en','ja','fr','it','es'].includes(language||''))throw Error('Ungültige Karte oder Sprache.');
 if(typeof content!=='string'||content.length>1400000||! /^[A-Za-z0-9+/=]+$/.test(content))throw Error('Bitte ein Foto bis 1 MB auswählen.');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(content),c=>c.charCodeAt(0));}catch{throw Error('Ungültiges Foto.');}if(bytes.length>1048576||bytes.length<4||bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)throw Error('Bitte ein gültiges JPEG-Foto bis 1 MB auswählen.');
 const card=await catalog('cards/'+cardId,language!);if(card.id!==cardId)throw Error('Karte konnte nicht zugeordnet werden.');
 const old=await d.prepare('SELECT * FROM card_images WHERE owner = ? AND card_id = ? AND language = ?').bind(owner,cardId,language).first();const path=owner+'/'+crypto.randomUUID()+'.jpg';await storage('object/'+bucket+'/'+path,{method:'POST',headers:{'Content-Type':'image/jpeg','x-upsert':'false'},body:bytes as unknown as BodyInit});
 try{await d.prepare('INSERT INTO card_images (id, owner, card_id, language, photo_path, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(owner,card_id,language) DO UPDATE').bind(old?.id||crypto.randomUUID(),owner,cardId,language,path,new Date().toISOString()).run();}catch(e){await removePhoto({owner,photo_path:path});throw e;}
 if(old)await removePhoto(old);return {ok:true};
}
