import {db,env,storage} from './data.ts';
import {catalog,physical} from './catalog.ts';
const bucket='card-photos';
function ownPath(path:string,owner:string){return path.startsWith(owner+'/')&&/^[a-f0-9-]+\.jpg$/.test(path.slice(owner.length+1));}
export async function photoUrl(row:any){if(!row?.photo_path||!ownPath(row.photo_path,row.owner))return null;try{const r=await storage('object/sign/'+bucket+'/'+row.photo_path,{method:'POST',body:JSON.stringify({expiresIn:3600})});return env.SUPABASE_URL+'/storage/v1'+r.signedURL;}catch{return null;}}
async function sharedImages(){const d=db();const accounts=(await d.prepare('SELECT user_id, username, active FROM portal_accounts').all()).results.filter((a:any)=>a.user_id&&a.active!==false);const allowed=new Set(accounts.map((a:any)=>a.user_id));return (await d.prepare('SELECT * FROM card_images ORDER BY updated_at DESC').all()).results.filter((i:any)=>allowed.has(i.owner));}
function findImage(images:any[],owner:string,cardId:string,language:string){return images.find(i=>i.owner===owner&&i.card_id===cardId&&i.language===language)||images.find(i=>i.card_id===cardId&&i.language===language);}
export async function catalogPhotos(cards:any[],owner:string,language:string){if(!cards.length)return cards;const images=await sharedImages();return Promise.all(cards.map(async c=>{const image=findImage(images,owner,c.id,language);return image?{...c,customImageUrl:await photoUrl(image),customPhotoId:image.id,customImageShared:image.owner!==owner}:c;}));}
export async function withPhotos(rows:any[]){if(!rows.length)return [];const images=await sharedImages(),urls=new Map<string,Promise<string|null>>(),result=[];for(let i=0;i<rows.length;i+=6)result.push(...await Promise.all(rows.slice(i,i+6).map(async r=>{const cardId=r.card_id||JSON.parse(r.data).id,image=findImage(images,r.owner,cardId,r.language)||{owner:r.owner};const key=image.owner+'/'+image.photo_path;if(!urls.has(key))urls.set(key,photoUrl(image));return {...r,customImageUrl:await urls.get(key),customPhotoId:image.id,customImageShared:image.owner!==r.owner};})));return result;}
export async function removePhoto(row:any){if(row.photo_path&&ownPath(row.photo_path,row.owner))await storage('object/'+bucket,{method:'DELETE',body:JSON.stringify({prefixes:[row.photo_path]})}).catch(()=>{});}
export async function savePhoto(owner:string,id:string,content:any,cardId?:string,language?:string){const d=db();if(!cardId){const row=await d.prepare('SELECT * FROM cards WHERE id = ? AND owner = ?').bind(id,owner).first();if(!row)throw Error('Bitte eine eigene Karte wählen.');cardId=row.card_id||JSON.parse(row.data).id;language=row.language;}
 if(!cardId||! /^[a-zA-Z0-9.-]{1,100}$/.test(cardId)||!physical({id:cardId})||!['de','en','ja','fr','it','es'].includes(language||''))throw Error('Ungültige Karte oder Sprache.');
 if(typeof content!=='string'||content.length>1400000||! /^[A-Za-z0-9+/=]+$/.test(content))throw Error('Bitte ein Foto bis 1 MB auswählen.');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(content),c=>c.charCodeAt(0));}catch{throw Error('Ungültiges Foto.');}if(bytes.length>1048576||bytes.length<4||bytes[0]!==255||bytes[1]!==216||bytes[2]!==255)throw Error('Bitte ein gültiges JPEG-Foto bis 1 MB auswählen.');
 let width=0,height=0;for(let offset=2;offset+4<bytes.length;){if(bytes[offset]!==255)throw Error('Ungültiges JPEG-Foto.');while(bytes[offset]===255)offset++;const marker=bytes[offset++];if(marker===218||marker===217)break;const length=(bytes[offset]<<8)|bytes[offset+1];if(length<2||offset+length>bytes.length)throw Error('Ungültiges JPEG-Foto.');if([192,193,194].includes(marker)){if(length<8)throw Error('Ungültiges JPEG-Foto.');height=(bytes[offset+3]<<8)|bytes[offset+4];width=(bytes[offset+5]<<8)|bytes[offset+6];}offset+=length;}
 if(width<1||height<1||width>1200||height>1200||bytes[bytes.length-2]!==255||bytes[bytes.length-1]!==217)throw Error('Bitte ein JPEG-Foto mit höchstens 1200 Pixeln pro Seite auswählen.');
 const card=await catalog('cards/'+cardId,language!);if(card.id!==cardId)throw Error('Karte konnte nicht zugeordnet werden.');
 const account=await d.prepare('SELECT role, active FROM portal_accounts WHERE user_id = ?').bind(owner).first();if(!account||account.active===false)throw Error('Konto nicht freigeschaltet.');
 const pending=(await d.prepare('SELECT id FROM photo_submissions WHERE owner = ? AND status = ?').bind(owner,'pending').all()).results;if(pending.length>=30)throw Error('Bitte warte auf die Freigabe deiner bisherigen Bilder.');
 const attempts=(await d.prepare('INSERT INTO login_attempts (id, attempts, window) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET attempts=attempts+1').bind('photo:'+owner+':'+new Date().toISOString().slice(0,10),Math.floor((Date.parse(new Date().toISOString().slice(0,10))+86400000)/600000)).all()).results;if(!attempts[0]||attempts[0].attempts>20)throw Error('Heute sind höchstens 20 Bilder möglich.');
 const old=await d.prepare('SELECT * FROM card_images WHERE owner = ? AND card_id = ? AND language = ?').bind(owner,cardId,language).first();const path=owner+'/'+crypto.randomUUID()+'.jpg';await storage('object/'+bucket+'/'+path,{method:'POST',headers:{'Content-Type':'image/jpeg','x-upsert':'false'},body:bytes as unknown as BodyInit});
 if(account.role!=='admin'){const submissionId=crypto.randomUUID();try{await d.prepare('INSERT INTO photo_submissions (id, owner, card_id, language, photo_path, card_name, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(submissionId,owner,cardId,language,path,card.name,'pending',new Date().toISOString()).run();}catch(e){await removePhoto({owner,photo_path:path});throw e;}return {ok:true,pending:true};}

 try{await d.prepare('INSERT INTO card_images (id, owner, card_id, language, photo_path, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(owner,card_id,language) DO UPDATE').bind(old?.id||crypto.randomUUID(),owner,cardId,language,path,new Date().toISOString()).run();}catch(e){await removePhoto({owner,photo_path:path});throw e;}
 if(old)await removePhoto(old);return {ok:true};
}
