import {db} from './data.ts';
import {japanesePublicProducts} from './japanese-supplement.ts';
export const publicGuideUrl='https://downloads.s3.cardmarket.com/productCatalog/priceGuide/price_guide_6.json';
const cacheId='public-cardmarket-japanese-supplement';
let running:Promise<any>|null=null;
// Stream the public guide: retain only verified product ids, not the full file.
export async function readPublicGuide(response:Response){if(!response.ok||!response.body)throw Error('Öffentlicher Preisguide nicht erreichbar.');const ids=new Set(Object.values(japanesePublicProducts)),prices:Record<string,any>={},reader=response.body.getReader(),decoder=new TextDecoder();let tail='',prefix='',bytes=0;try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>45_000_000)throw Error('Preisguide zu groß.');const part=decoder.decode(value,{stream:true});if(prefix.length<1500)prefix=(prefix+part).slice(0,1500);tail+=part;const pattern=/\{[^{}]*\}/g;let m:RegExpExecArray|null,last=0;while((m=pattern.exec(tail))){last=pattern.lastIndex;if(!/"idProduct"\s*:/.test(m[0]))continue;const row=JSON.parse(m[0]);if(ids.has(row.idProduct)&&row.idCategory===51)prices[row.idProduct]=row;}if(last)tail=tail.slice(last);const start=tail.lastIndexOf('{');if(start>=0)tail=tail.slice(start);else if(tail.length>2000)tail=tail.slice(-2000);if(tail.length>65536)throw Error('Ungültiger Preisguide.');}const updated=prefix.match(/"createdAt"\s*:\s*"([^"]+)"/)?.[1];if(!updated||!Number.isFinite(Date.parse(updated))||!Object.keys(prices).length)throw Error('Ungültiger Preisguide.');return {updated,prices:Object.fromEntries(Object.entries(prices).map(([id,p])=>[id,{...p,updated}]))};}finally{await reader.cancel().catch(()=>{});}}
async function guide(){const stored=(await db().prepare('SELECT data, updated_at FROM market_quotes WHERE id = ?').bind(cacheId).first())?.data||{};const day=new Date().toISOString().slice(0,10);if(stored.checkedDay===day||stored.retryAfter>Date.now())return stored;try{const fresh=await readPublicGuide(await fetch(publicGuideUrl,{signal:AbortSignal.timeout(30000)}));const merged={updated:fresh.updated,prices:{...stored.prices,...fresh.prices},checkedDay:day};await db().prepare('INSERT INTO market_quotes (id,data,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(cacheId,merged,new Date().toISOString()).run();return merged;}catch{const saved={...stored,retryAfter:Date.now()+900000};await db().prepare('INSERT INTO market_quotes (id,data,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(cacheId,saved,new Date().toISOString()).run();return saved;}}
export async function withPublicJapaneseTrend(card:any,language:string){const productId=japanesePublicProducts[card.id];if(language!=='ja'||!productId||card.pricing?.cardmarket?.trend>0)return card;if(!running)running=guide().finally(()=>{running=null;});const g=await running,p=g.prices?.[productId];if(!p||!(p.trend>0))return {...card,priceNotice:'Für diese Ausgabe liegt kein öffentlicher Trendpreis vor. Einen aktuellen Cardmarket-Preis kannst du manuell einreichen.'};const pricing={...p,unit:'EUR',updated:p.updated||g.updated,source:'Cardmarket-Trend · japanische Ausgabe',sourceUrl:publicGuideUrl};return {...card,pricing:{...card.pricing,cardmarket:pricing},variants_detailed:(card.variants_detailed||[]).map((v:any)=>v.thirdParty?.cardmarket===productId?{...v,pricing:{...v.pricing,cardmarket:pricing}}:v)};}
