// Shared by the browser and API: punctuation-insensitive, ranked name matching.
export function normalize(text:string){return String(text||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim().replace(/^m (?=[a-z])/,'mega ');}
function distance(a:string,b:string){if(Math.abs(a.length-b.length)>2)return 99;const d=Array.from({length:a.length+1},(_,i)=>Array.from({length:b.length+1},(_,j)=>i===0?j:j===0?i:0));for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+Number(a[i-1]!==b[j-1]));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])d[i][j]=Math.min(d[i][j],d[i-2][j-2]+1);}return d[a.length][b.length];}
export function nameScore(name:string,query:string){const n=normalize(name),q=normalize(query);if(!q)return 0;if(n===q)return 0;if(n.replaceAll(' ','')===q.replaceAll(' ',''))return 1;if(n.includes(q))return 2+(n.startsWith(q)?0:1);const words=n.split(' '),terms=q.split(' ');let score=4;for(const t of terms){if(words.includes(t))continue;if(words.some(w=>w.startsWith(t))){score+=1;continue;}const tolerance=t.length>=8?2:t.length>=4?1:0;if(!tolerance)return Infinity;const diff=Math.min(...words.map(w=>distance(t,w)));if(diff>tolerance)return Infinity;score+=10+diff;}return score;}
export function rankNames<T>(rows:T[],query:string,name:(row:T)=>string){return rows.map((row,index)=>({row,index,score:nameScore(name(row),query)})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>a.score-b.score||a.index-b.index).map(x=>x.row);}
export function suggestions(names:string[],query:string){return [...new Set(rankNames(names,query,n=>n))].slice(0,5);}

export function parseNumber(q:string){const text=q.split('/')[0].trim().toUpperCase().replace(/[\s-]/g,'');const m=text.match(/^(SVP|MEP|SWSH|SM|XY|BW|HGSS|DP)(\d+)$/);const prefixSets:Record<string,string>={SVP:'svp',MEP:'mep',SWSH:'swshp',SM:'smp',XY:'xyp',BW:'bwp',HGSS:'hgssp',DP:'dpp'};return {text,set:m?prefixSets[m[1]]:'',number:m?(['SVP','MEP'].includes(m[1])?m[2].padStart(3,'0'):m[1]+m[2].padStart(['SWSH','SM'].includes(m[1])?3:2,'0')):text};}
export function cardMatches(c:any,q:string){const n=parseNumber(q).number,local=String(c.localId).toUpperCase();if(/^\d+$/.test(n))return /^\d+$/.test(local)&&Number(local)===Number(n);if(/^[A-Z]+\d+$/.test(n))return local===n;return Number.isFinite(nameScore(c.name,q))||normalize(c.id).replaceAll(' ','')===normalize(q).replaceAll(' ','');}
