import {env} from 'cloudflare:workers';
import {db} from './data';
function accounts():Record<string,string>{const values=JSON.parse(env.USER_ACCOUNTS_JSON||'{}');if(Object.keys(values).length!==2)throw Error('Die zwei Benutzerkonten sind noch nicht konfiguriert.');return values;}
export function cookie(r:Request,name:string){return (r.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)||'';}
function allowed(email:string){return Object.values(accounts()).some(value=>String(value).toLowerCase()===email?.toLowerCase());}
async function supabase(path:string,options:RequestInit={},token?:string){if(!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)throw Error('Die Anmeldung ist noch nicht eingerichtet.');const url=new URL(env.SUPABASE_URL);if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co'))throw Error('Ungültige Supabase-Projektadresse.');return fetch(url.origin+'/auth/v1/'+path,{...options,headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers},signal:AbortSignal.timeout(15000)});}
export async function getUser(request:Request){const token=cookie(request,'__Host-pv-access');if(!token)return null;const r=await supabase('user',{},token);if(!r.ok)return null;const u:any=await r.json();if(!u.id||!allowed(u.email))return null;return {userId:u.id,username:Object.entries(accounts()).find(([,email])=>email.toLowerCase()===u.email.toLowerCase())?.[0]||'Sammler'};}
function session(data:any){const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});h.append('Set-Cookie',`__Host-pv-access=${data.access_token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.min(Number(data.expires_in)||3600,3600)}`);h.append('Set-Cookie',`__Host-pv-refresh=${data.refresh_token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`);return new Response(JSON.stringify({ok:true}),{headers:h});}
export async function auth(request:Request){const p=new URL(request.url).pathname;if(request.method==='GET'){const user=await getUser(request);return Response.json(user||{error:'Nicht angemeldet.'},{status:user?200:401});}
 if(request.method!=='POST')return Response.json({error:'Methode nicht erlaubt.'},{status:405});
 const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Anfrage abgelehnt.'},{status:403});
 if(p.endsWith('/logout')){const token=cookie(request,'__Host-pv-access');if(token)await supabase('logout',{method:'POST'},token).catch(()=>{});const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});for(const name of ['__Host-pv-access','__Host-pv-refresh'])h.append('Set-Cookie',`${name}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);return new Response('{"ok":true}',{headers:h});}
 if(p.endsWith('/refresh')){const token=cookie(request,'__Host-pv-refresh');if(!token)return Response.json({error:'Bitte erneut anmelden.'},{status:401});const r=await supabase('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:token})});const data:any=await r.json();if(!r.ok||!data.user?.email||!allowed(data.user.email))return Response.json({error:'Bitte erneut anmelden.'},{status:401});return session(data);}
 const ip=request.headers.get('CF-Connecting-IP')||'unknown',digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const hash=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');const window=Math.floor(Date.now()/600000),key=hash+'|'+window;
 await db().prepare('INSERT INTO login_attempts (id, attempts, window) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET attempts=attempts+1').bind(key,window).run();const row:any=await db().prepare('SELECT attempts FROM login_attempts WHERE id=?').bind(key).first();if(row.attempts>10)return Response.json({error:'Zu viele Anmeldeversuche. Bitte in zehn Minuten erneut versuchen.'},{status:429});
 const b:any=await request.json(),username=String(b.username||'').trim(),email=Object.entries(accounts()).find(([name])=>name.toLowerCase()===username.toLowerCase())?.[1];if(!email||typeof b.password!=='string'||b.password.length>1024)return Response.json({error:'Benutzername oder Passwort stimmt nicht.'},{status:401});
 const r=await supabase('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password:b.password})});const data:any=await r.json();if(!r.ok||!data.user?.email||!allowed(data.user.email))return Response.json({error:'Benutzername oder Passwort stimmt nicht.'},{status:401});return session(data);
}
