import {useEffect,useState} from 'react';
import {api} from './api';
export default function AdminPanel(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{setData(await api('?op=moderation'));}catch(e:any){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function review(id:string,decision:string){setBusy(true);setError('');setNotice('');try{const result=await api('',{op:'review-photo',id,decision});setNotice(result.alreadyReviewed?'Dieses Bild wurde bereits geprüft.':decision==='approved'?'Bild freigegeben.':'Bild abgelehnt.');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="admin-page"><div className="page-heading"><div><div className="eyebrow">ADMINISTRATION</div><h1>Verwaltung</h1><p>Prüfe neue Kartenbilder und behalte die freigeschalteten Nutzer im Blick.</p></div><button className="secondary" disabled={busy} onClick={load}>Neu laden</button></div>{error&&<p role="alert" className="message error">{error}</p>}{notice&&<p role="status" className="message">{notice}</p>}<h2>Bildfreigaben {data?'· '+data.total:''}</h2><p>Prüfe Karte, Nummer und Sprache. Freigegebene Bilder sind für alle Sammler sichtbar. Abgelehnte Bilder werden nicht veröffentlicht.</p><div className="moderation-grid">{data?.images.map((image:any)=><article className="settings-card" key={image.id}>{image.image?<img className="moderation-photo" src={image.image} alt={'Eingereichtes Bild für '+image.cardName}/>:<p>Vorschau nicht verfügbar</p>}<h3>{image.cardName}</h3><p>{image.cardId} · {image.language.toUpperCase()}</p><small>Von {image.username} · {new Date(image.createdAt).toLocaleDateString('de-DE')}</small><div className="button-row"><button className="primary" disabled={busy||!image.image} onClick={()=>review(image.id,'approved')}>Freigeben</button><button className="secondary" disabled={busy} onClick={()=>review(image.id,'rejected')}>Ablehnen</button></div></article>)}</div>{data?.total===0&&<p className="empty">Keine Bilder warten auf Freigabe.</p>}{data?.total>60&&<p>Weitere Bilder erscheinen nach der Prüfung dieser Einträge.</p>}<h2>Freigeschaltete Nutzer</h2><p>Neue Konten werden auf Einladung durch den Administrator eingerichtet. Nutzer pflegen ihre eigenen Sammlungen und reichen Bilder zur Freigabe ein.</p><div className="admin-user-list">{data?.users.map((u:any)=><div key={u.username}><strong>{u.username}</strong><span>{u.role==='admin'?'Administrator':'Sammler'}</span></div>)}</div></section>;
}
