export const sortChoices=[['number-asc','Nummer ↑'],['number-desc','Nummer ↓'],['price-asc','Preis ↑'],['price-desc','Preis ↓'],['type-asc','Typ A–Z'],['type-desc','Typ Z–A'],['name-asc','Name A–Z'],['name-desc','Name Z–A']];
export function isChase(rarity:string){return /special.?illustration|besondere illustration|\bsar\b|\bsir\b|hyper|secret|geheim|versteckt|rainbow/i.test(rarity||'');}
const typeNames:Record<string,string>={Grass:'Pflanze',Fire:'Feuer',Water:'Wasser',Lightning:'Elektro',Psychic:'Psycho',Fighting:'Kampf',Darkness:'Unlicht',Metal:'Metall',Fairy:'Fee',Dragon:'Drache',Colorless:'Farblos'};
export function cardTypes(c:any):string[]{return c.types?.length?c.types.map((t:string)=>typeNames[t]||t):[c.category==='Energy'?'Energie':c.category==='Pokemon'?'Pokémon':c.category||'Nicht angegeben'];}
export function matchesType(c:any,type:string){return type==='all'||cardTypes(c).includes(type);}
export function typeLabel(c:any){return cardTypes(c).join(', ');}
export function compareCards(a:any,b:any,sort:string,price:(c:any)=>number|null){const [field,direction]=sort.split('-'),sign=direction==='desc'?-1:1;let result=0;if(field==='price'){const x=price(a),y=price(b);if(x===null||y===null)return x===y?number(a,b):x===null?1:-1;result=x-y;}else if(field==='number')result=number(a,b);else if(field==='type')result=typeLabel(a).localeCompare(typeLabel(b),'de',{numeric:true});else result=String(a.name).localeCompare(String(b.name),'de',{numeric:true});return sign*result||number(a,b);}
function number(a:any,b:any){return String(a.localId).localeCompare(String(b.localId),'de',{numeric:true})||String(a.id).localeCompare(String(b.id));}
export default function CardTools({sort,onSort,type,onType,rarity,onRarity,cards,includeRelevance=false,includeRecent=false}:{sort:string,onSort:(s:string)=>void,type:string,onType:(s:string)=>void,rarity:string,onRarity:(s:string)=>void,cards:any[],includeRelevance?:boolean,includeRecent?:boolean}){const types=[...new Set(cards.flatMap(cardTypes))].filter(t=>t!=='Nicht angegeben').sort();const rarities=[...new Set(cards.map(c=>c.rarity).filter(Boolean))].sort();return <div className="card-controls"><label>Sortieren<select value={sort} onChange={e=>onSort(e.target.value)}>{includeRecent&&<option value="new">Zuletzt gespeichert</option>}{includeRelevance&&<option value="relevance">Beste Treffer</option>}{sortChoices.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Kartentyp<select value={type} onChange={e=>onType(e.target.value)}><option value="all">Alle Typen</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Seltenheit<select value={rarity} onChange={e=>onRarity(e.target.value)}><option value="all">Alle Seltenheiten</option><option value="chase">SAR / SIR & höchste Seltenheiten</option>{rarities.map(r=><option key={r} value={r}>{r}</option>)}</select></label><small className="sort-note">Preis pro Karte · fehlende Werte stehen zuletzt.</small></div>;}
