import {useEffect,useRef,useState} from 'react';
import {Camera,ScanLine,RefreshCw} from 'lucide-react';
import {prepare} from './photo-upload';
import {scanText} from './scan-text';
type OCRWorker={recognize:(image:string)=>Promise<{data:{text:string}}>,terminate:()=>Promise<void>};
type OCR={createWorker:(languages:string,mode:number,options:any)=>Promise<OCRWorker>};
let engine:Promise<OCR>|undefined;
function loadOCR(){if(!engine)engine=new Promise<OCR>((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';script.crossOrigin='anonymous';script.onload=()=>{const api=(window as unknown as {Tesseract:OCR}).Tesseract;api?resolve(api):reject(Error('Scanner konnte nicht geladen werden.'));};script.onerror=()=>{script.remove();engine=undefined;reject(Error('Scanner-Download fehlgeschlagen. Du kannst Name und Nummer unten eingeben.'));};document.head.appendChild(script);});return engine;}
export default function CardScanner({language,onSearch}:{language:string,onSearch:(number:string,name:string)=>Promise<any>}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(''),[number,setNumber]=useState(''),[name,setName]=useState('');const worker=useRef<OCRWorker|null>(null),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;worker.current?.terminate().catch(()=>{});};},[]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const scan=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');setNumber('');setName('');setPreview(URL.createObjectURL(file));setProgress('Scanner wird geladen …');try{const data='data:image/jpeg;base64,'+await prepare(file);const ocr=await loadOCR();if(!mounted.current)return;worker.current=await ocr.createWorker(language==='de'?'deu+eng':'eng',1,{logger:(m:any)=>{if(mounted.current&&m.status==='recognizing text')setProgress('Karte wird gelesen: '+Math.round(m.progress*100)+' %');}});if(!mounted.current){await worker.current.terminate();return;}const result=await worker.current.recognize(data);if(mounted.current){const found=scanText(result.data.text);setNumber(found.number);setName(found.name);if(!found.number&&!found.name)setError('Kein eindeutiger Text erkannt. Bitte Name oder Kartennummer ergänzen.');}}catch(e:any){if(mounted.current)setError(e.message||'Foto konnte nicht gelesen werden. Bitte ein scharfes Foto ohne Spiegelungen aufnehmen.');}finally{await worker.current?.terminate().catch(()=>{});worker.current=null;if(mounted.current){setBusy(false);setProgress('');}}};
 return <div className="card-scanner"><button className="secondary" type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><ScanLine size={18}/>{open?'Scanner schließen':'Karte mit Kamera suchen'}</button>{open&&<div className="scan-panel"><p>Die ganze Kartenvorderseite gerade und ohne Spiegelungen fotografieren. Name und Nummer werden auf deinem Gerät gelesen.</p><div className="photo-actions"><label className="photo-button"><span><Camera size={18}/>Kamera öffnen</span><input aria-label="Karte scannen mit Kamera" type="file" accept="image/*" capture="environment" disabled={busy} onChange={scan}/></label><label className="photo-button"><span>Foto auswählen</span><input aria-label="Kartenfoto zum Scannen auswählen" type="file" accept="image/*" disabled={busy} onChange={scan}/></label></div>{preview&&<img className="scan-preview" src={preview} alt="Dein aufgenommenes Kartenfoto"/>}{busy&&<p role="status"><RefreshCw className="spin" size={16}/>{progress}</p>}{error&&<p role="alert" className="negative">{error}</p>}<div className="fields-two"><label>Erkannte Nummer<input value={number} onChange={e=>setNumber(e.target.value)} placeholder="z. B. 284 oder SVP 027"/></label><label>Erkannter Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Mega Gengar ex"/></label></div><button type="button" className="primary" disabled={busy||(!number.trim()&&!name.trim())} onClick={async()=>{setBusy(true);setError('');try{await onSearch(number.trim(),name.trim());}catch(e:any){setError(e.message)}finally{if(mounted.current)setBusy(false)}}}>Treffer suchen</button><small>Erkennung bitte prüfen. Erst den passenden Treffer öffnen und zur Sammlung hinzufügen. Das Scan-Foto wird nicht automatisch hochgeladen.</small></div>}</div>;
}
