import {useEffect,useRef,useState} from 'react';
import {Camera,ScanLine,RefreshCw} from 'lucide-react';
import {scanRegions} from './scan-text';
import {fullCard,clampCrop,regionImage,openScanImage,nameRegion,footerRegions,type CardCrop} from './scan-regions';
type OCRWorker={setParameters:(p:Record<string,string>)=>Promise<void>,recognize:(image:string)=>Promise<{data:{text:string,confidence:number}}>,terminate:()=>Promise<void>};
type OCR={createWorker:(languages:string,mode:number,options:any)=>Promise<OCRWorker>};
let engine:Promise<OCR>|undefined;
function loadOCR(){if(!engine)engine=new Promise<OCR>((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';script.crossOrigin='anonymous';script.onload=()=>{const api=(window as unknown as {Tesseract:OCR}).Tesseract;api?resolve(api):reject(Error('Scanner konnte nicht geladen werden.'));};script.onerror=()=>{script.remove();engine=undefined;reject(Error('Scanner-Download fehlgeschlagen. Du kannst Name und Nummer unten eingeben.'));};document.head.appendChild(script);});return engine;}
export default function CardScanner({language,onSearch}:{language:string,onSearch:(number:string,name:string)=>Promise<any>}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(''),[number,setNumber]=useState(''),[name,setName]=useState(''),[total,setTotal]=useState(''),[crop,setCrop]=useState<CardCrop>(fullCard);const imageRef=useRef<HTMLImageElement|null>(null),start=useRef<{x:number,y:number}|null>(null);const worker=useRef<OCRWorker|null>(null),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;worker.current?.terminate().catch(()=>{});};},[]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const readRegions=async(image:HTMLImageElement,area:CardCrop)=>{setBusy(true);setError('');setNumber('');setName('');setTotal('');setProgress('Scanner wird geladen …');try{const ocr=await loadOCR();if(!mounted.current)return;worker.current=await ocr.createWorker(language==='de'?'deu+eng':'eng',1,{});if(!mounted.current){await worker.current.terminate();return;}setProgress('Namenszeile oben wird gelesen …');await worker.current.setParameters({tessedit_pageseg_mode:'6'});const header=await worker.current.recognize(regionImage(image,area,nameRegion));await worker.current.setParameters({tessedit_pageseg_mode:'11'});const footers=[];for(let i=0;i<footerRegions.length;i++){if(!mounted.current)return;setProgress(['Nummer am unteren Rand wird gelesen …','Nummer unten links wird gelesen …','Nummer unten mittig wird gelesen …','Nummer unten rechts wird gelesen …'][i]);const r=await worker.current.recognize(regionImage(image,area,footerRegions[i]));footers.push(r.data);}if(mounted.current){const found=scanRegions(header.data.text,footers);setNumber(found.number+(found.total?'/'+found.total:''));setTotal('');setName(found.name);if(found.uncertain)setError(found.number?'Nummer unsicher: Bitte mit dem Aufdruck vergleichen.':'Keine eindeutige Kartennummer erkannt. Kartenbereich eingrenzen oder Nummer ergänzen.');}}catch(e:any){if(mounted.current)setError(e.message||'Bildbereiche konnten nicht gelesen werden.');}finally{await worker.current?.terminate().catch(()=>{});worker.current=null;if(mounted.current){setBusy(false);setProgress('');}}};
 const scan=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setBusy(true);try{const image=await openScanImage(file);imageRef.current=image;setPreview(URL.createObjectURL(file));setCrop(fullCard);await readRegions(image,fullCard);}catch(e:any){setError(e.message);setBusy(false);}};
 const point=(e:React.PointerEvent<HTMLDivElement>)=>{const rect=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))};};

 return <div className="card-scanner"><button className="secondary" type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><ScanLine size={18}/>{open?'Scanner schließen':'Karte mit Kamera suchen'}</button>{open&&<div className="scan-panel"><p>Nur die Kartenvorderseite gerade fotografieren. Der Scanner liest die Namenszeile oben und sucht die Nummer unten links, mittig und rechts.</p><div className="photo-actions"><label className="photo-button"><span><Camera size={18}/>Kamera öffnen</span><input aria-label="Karte scannen mit Kamera" type="file" accept="image/*" capture="environment" disabled={busy} onChange={scan}/></label><label className="photo-button"><span>Foto auswählen</span><input aria-label="Kartenfoto zum Scannen auswählen" type="file" accept="image/*" disabled={busy} onChange={scan}/></label></div>{preview&&<><div className="scan-crop" onPointerDown={e=>{if(busy)return;start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!start.current||busy)return;const p=point(e),a=start.current;setCrop(clampCrop({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(a.x-p.x),h:Math.abs(a.y-p.y)}));}} onPointerUp={()=>{start.current=null;}} onPointerCancel={()=>{start.current=null;}}><img src={preview} draggable={false} alt="Kartenfoto: Ziehe einen Rahmen um die Kartenvorderseite"/><span className="scan-card-frame" style={{left:crop.x*100+'%',top:crop.y*100+'%',width:crop.w*100+'%',height:crop.h*100+'%'}}><span className="scan-name-guide">Name</span><span className="scan-footer-guide">← Kartennummer →</span></span></div><small>Falls Hintergrund oder Hülle im Foto sind: Ziehe von einer Kartenecke zur gegenüberliegenden Ecke und tippe auf „Bereiche erneut lesen“.</small><div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>imageRef.current&&readRegions(imageRef.current,crop)}>Bereiche erneut lesen</button><button type="button" className="text-btn" disabled={busy} onClick={()=>setCrop(fullCard)}>Ganzes Bild</button></div></>}{busy&&<p role="status"><RefreshCw className="spin" size={16}/>{progress}</p>}{error&&<p role="alert" className="negative">{error}</p>}<div className="fields-two"><label>Erkannte Nummer<input value={number} onChange={e=>setNumber(e.target.value)} placeholder="z. B. 284/217 oder SVP 027"/></label><label>Erkannter Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Mega Gengar ex"/></label></div><button type="button" className="primary" disabled={busy||(!number.trim()&&!name.trim())} onClick={async()=>{setBusy(true);setError('');try{await onSearch(number.trim()+(total?'/'+total:''),name.trim());}catch(e:any){setError(e.message)}finally{if(mounted.current)setBusy(false)}}}>Treffer suchen</button><small>Erkennung bitte prüfen. Erst den passenden Treffer öffnen und zur Sammlung hinzufügen. Das Scan-Foto wird nicht automatisch hochgeladen.</small></div>}</div>;
}
