import {useId} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import {lastThirtyDays,seedCardHistory} from '../supabase/functions/pokevault/card-history';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const label=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'});
export default function CardHistoryChart({row}:{row:any}){
 const titleId=useId(),data=seedCardHistory(row),points=lastThirtyDays(data.cardPriceHistory||[],row.grading||''),observed=points.filter(p=>p.raw!==null||p.graded!==null),comparison=!!data.gradedQuote?.comparison;
 return <section className="history-panel card-history-panel" aria-labelledby={titleId}><div className="history-heading"><div><h3 id={titleId}>Wertverlauf · letzte 30 Tage</h3><p>Richtpreise pro Karte · gespeicherte Tagesstände</p></div></div>{observed.length?<div className="chart-container" role="img" aria-label={'Wertverlauf der Karte über 30 Tage. '+observed.length+' gespeicherte Tagesstände.'}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:12,right:12,bottom:6,left:0}}><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="day" tickFormatter={label} tick={{fontSize:11,fill:'var(--muted)'}} tickLine={false} axisLine={false} minTickGap={35}/><YAxis width={65} tickFormatter={v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(v)+' €'} tick={{fontSize:11,fill:'var(--muted)'}} axisLine={false} tickLine={false} domain={[0,'auto']}/><Tooltip labelFormatter={v=>label(String(v))} formatter={(v:any,name:any)=>[euro(Number(v)),name]} contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:12,color:'var(--ink)'}}/><Legend wrapperStyle={{fontSize:12}}/><Line type="linear" dataKey="raw" name="Ungegradet" stroke="var(--blue)" strokeWidth={2.5} dot={{r:3}} connectNulls={false} isAnimationActive={false}/>{row.grading&&<Line type="linear" dataKey="graded" name={row.grading+(data.gradedQuote?.estimated||comparison?' · Schätzwert':'')} stroke="var(--red)" strokeWidth={2.5} dot={{r:3}} connectNulls={false} isAnimationActive={false}/>}</LineChart></ResponsiveContainer></div>:<p>Noch keine Preisstände verfügbar.</p>}<p className="history-caption">{observed.length<30?'Bisher '+observed.length+' von 30 Tagen erfasst. Frühere Tagespreise liegen noch nicht vor.':'30-Tage-Verlauf aus gespeicherten Preisständen.'} Fehlende Tage bleiben Lücken. Eigene Werte und Stückzahl verändern diese Marktpreiskurve nicht.</p><details className="history-data"><summary>Tageswerte anzeigen</summary><div className="history-table-scroll"><table><thead><tr><th>Tag</th><th>Ungegradet</th>{row.grading&&<th>{row.grading}</th>}</tr></thead><tbody>{observed.map(p=><tr key={p.day}><td>{label(p.day)}</td><td>{p.raw===null?'Offen':euro(p.raw)}</td>{row.grading&&<td>{p.graded===null?'Offen':euro(p.graded)}</td>}</tr>)}</tbody></table></div></details></section>;
}
