import {useEffect,useState,useRef} from 'react';
import {ArrowLeft,Search,Folder,Plus,ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {api} from './api';
import CardImage from './card-image';
import {normalize,rankNames,suggestions,cardMatches} from '../supabase/functions/pokevault/search';
const languages:Record<string,string>={de:'Deutsch',en:'Englisch'};
const promo=(s:any)=>/promo/i.test(s.name)||['basep','dpp','hgssp','bwp','xyp','smp','swshp','svp','mep'].includes(s.id);
const clean=normalize;
const eur=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const PAGE_SIZE=12;
export default function CatalogBrowser({onChoose}:{onChoose:(id:string,language:string)=>Promise<any>}){
 const requestId=useRef(0);
 const [priceRevision,setPriceRevision]=useState(0);
 const [language,setLanguage]=useState('de'),[sets,setSets]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[cards,setCards]=useState<any[]>([]),[tab,setTab]=useState('sets'),[query,setQuery]=useState(''),[folderQuery,setFolderQuery]=useState(''),[page,setPage]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[prices,setPrices]=useState<Record<string,any>>({}),[choosing,setChoosing]=useState(false),[searched,setSearched]=useState(false);
 useEffect(()=>{let cancelled=false;requestId.current++;setLoading(true);setError('');setSelected(null);setCards([]);setQuery('');setFolderQuery('');setPage(0);setPrices({});api('?op=sets&lang='+language).then(s=>{if(!cancelled)setSets(s);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[language]);
 const visibleSets=sets.filter(s=>(tab!=='promos'||promo(s))&&(tab!=='sets'||!promo(s))&&clean(s.name+' '+s.id).includes(clean(folderQuery)));
 const filtered=selected?rankNames(cards.filter(c=>!query||cardMatches(c,query)),/^\d|^(SVP|MEP|SWSH|SM|XY|BW|HGSS|DP)\s*\d/i.test(query)?'':query,(c:any)=>c.name):rankNames(cards.filter(c=>!query||cardMatches(c,query)),/^\d|^(SVP|MEP|SWSH|SM|XY|BW|HGSS|DP)\s*\d/i.test(query)?'':query,(c:any)=>c.name);
 const hints=query.length>=3?suggestions(cards.map(c=>c.name),query):[];
 const visible=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
 const ids=visible.map(c=>c.id).join(',');
 useEffect(()=>{if(!ids)return;let cancelled=false;const missing=ids.split(',').filter(id=>!prices[id]);const chunks=[];for(let i=0;i<missing.length;i+=6)chunks.push(missing.slice(i,i+6));Promise.all(chunks.map(async chunk=>{try{const rows=await api('?op=prices&lang='+language+'&ids='+encodeURIComponent(chunk.join(',')));if(!cancelled)setPrices(p=>({...p,...Object.fromEntries(rows.map((r:any)=>[r.id,r]))}));}catch{if(!cancelled)setPrices(p=>({...p,...Object.fromEntries(chunk.map(id=>[id,{error:true}]))}));}}));return()=>{cancelled=true;};},[ids,language,priceRevision]);
 const open=async(s:any)=>{const ticket=++requestId.current;setLoading(true);setError('');setSelected(s);setQuery('');setPage(0);setCards([]);try{const data=await api('?op=set&lang='+language+'&id='+encodeURIComponent(s.id));if(ticket===requestId.current){setSelected(data);setCards(data.cards||[]);}}catch(e:any){if(ticket===requestId.current)setError(e.message);}finally{if(ticket===requestId.current)setLoading(false);}};
 const back=()=>{requestId.current++;setLoading(false);setSelected(null);setCards([]);setQuery('');setPage(0);setError('');setSearched(false);};
 const globalSearch=async(e:any)=>{e.preventDefault();const ticket=++requestId.current;setLoading(true);setError('');setPage(0);try{const data=await api('?op=search&lang='+language+'&q='+encodeURIComponent(query));if(ticket===requestId.current){setCards(data);setSearched(true);}}catch(e:any){if(ticket===requestId.current)setError(e.message);}finally{if(ticket===requestId.current)setLoading(false);}};
 const choose=async(id:string)=>{setChoosing(true);setError('');try{await onChoose(id,language);}catch(e:any){setError(e.message);}finally{setChoosing(false);}};
 return <section className="catalog-browser"><div className="catalog-top"><div><h2>{selected?selected.name:'Kartenkatalog'}</h2><p>{selected?`${cards.length} katalogisierte Karten${selected.releaseDate?' · '+new Date(selected.releaseDate+'T12:00:00').toLocaleDateString('de-DE'):''}`:'Set öffnen, Karte finden und zur Sammlung hinzufügen.'}</p></div><label className="catalog-language">Kartensprache<select value={language} onChange={e=>setLanguage(e.target.value)}>{Object.entries(languages).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>
 {error&&<p role="alert" className="message error">{error}</p>}
 {selected?<><button type="button" className="catalog-back" onClick={back}><ArrowLeft size={17}/>Alle {promo(selected)?'Promo-Ordner':'Sets'}</button><div className="catalog-filter"><Search size={18}/><input aria-label="Karten im Set suchen" list="catalog-card-names" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Kartenname auswählen oder Nummer eingeben …"/><datalist id="catalog-card-names">{[...new Set(cards.map(c=>c.name))].sort().map(name=><option key={name} value={name}/>)}</datalist></div></>:<><div className="catalog-tabs" role="group" aria-label="Katalogbereich">{[['sets','Erweiterungen'],['promos','Promo-Ordner'],['search','Kartensuche']].map(([id,name])=><button type="button" key={id} aria-pressed={tab===id} className={tab===id?'selected':''} onClick={()=>{requestId.current++;setLoading(false);setTab(id);setCards([]);setQuery('');setPage(0);setSearched(false);}}>{name}</button>)}</div>{tab==='search'?<form className="catalog-global-search" onSubmit={globalSearch}><label>Kartenname oder Nummer<input required value={query} onChange={e=>setQuery(e.target.value)} placeholder="z. B. Mega Gengar, gengra oder SVP 027"/></label><button className="primary" disabled={loading}><Search size={17}/>Suchen</button><small className="search-hint">Bindestriche und Großschreibung sind egal. Kleine Tippfehler werden berücksichtigt.</small></form>:<div className="catalog-filter"><Search size={18}/><input aria-label="Sets suchen" list="catalog-set-names" value={folderQuery} onChange={e=>setFolderQuery(e.target.value)} placeholder={tab==='promos'?'Promo-Ordner suchen …':'Set suchen, z. B. 30 Jahre oder Erhabene Helden …'}/><datalist id="catalog-set-names">{sets.map(s=><option key={s.id} value={s.name}/>)}</datalist></div>}</>}
 {loading?<div role="status" className="catalog-loading"><RefreshCw className="spin" size={23}/>Katalog wird geladen …</div>:!selected&&tab!=='search'?<div className="set-folders">{visibleSets.map((s,index)=><button className="set-folder" key={s.id} type="button" onClick={()=>open(s)}><span className="set-folder-art">{s.logo?<img src={s.logo+'.webp'} alt="" loading="lazy" onError={e=>{e.currentTarget.hidden=true;}}/>:<Folder size={30}/>}</span><span className="set-folder-info"><strong>{s.name}</strong><small>{s.cardCount?.total||0} Karten · {s.id.toUpperCase()}</small>{tab==='sets'&&!folderQuery&&index<6&&<span className="set-new">Aktuell</span>}</span><ChevronRight size={18}/></button>)}{!visibleSets.length&&<p>Kein passendes Set in dieser Sprache gefunden.</p>}</div>:<><div className="catalog-results-meta"><span>{filtered.length} {selected?'Karten im Set':'Treffer'}</span><small>Cardmarket-Richtpreise via TCGdex · Variante beim Hinzufügen prüfen</small><button type="button" className="text-btn" onClick={()=>{setPrices({});setPriceRevision(v=>v+1);}} disabled={!visible.length}><RefreshCw size={15}/>Preise neu laden</button></div>{hints.length>0&&<div className="search-suggestions"><small>Passende Namen:</small>{hints.map(name=><button type="button" key={name} onClick={()=>{setQuery(name);setPage(0);}}>{name}</button>)}</div>}<div className="catalog-cards">{visible.map(c=>{const p=prices[c.id];return <button type="button" key={c.id} className="catalog-card" disabled={choosing} onClick={()=>choose(c.id)}><span className="catalog-card-art"><CardImage card={c} language={language}/></span><span className="catalog-card-text"><small>Nr. {c.localId}{!selected?' · '+(c.setName||c.id.slice(0,c.id.lastIndexOf('-'))):''}</small><strong>{c.name}</strong><span className="catalog-card-price">{!p?'Preis lädt …':p.error?'Preisabruf fehlgeschlagen':p.price===null?'Preis offen':eur(p.price)}<Plus size={16}/></span>{p?.updated&&<small>Preisquelle: {new Date(p.updated).toLocaleDateString('de-DE')}</small>}</span></button>;})}</div>{!filtered.length&&(selected||searched)&&<p className="catalog-no-results">Keine passenden Karten gefunden.</p>}{filtered.length>PAGE_SIZE&&<div className="catalog-pagination"><button type="button" className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/>Zurück</button><span>{page+1} / {pageCount}</span><button type="button" className="secondary" disabled={page+1>=pageCount} onClick={()=>setPage(p=>p+1)}>Weiter<ChevronRight size={17}/></button></div>}{!selected&&searched&&<small>Bis zu 60 Suchtreffer. Für alle Karten ein Set öffnen.</small>}</>}
 </section>;
}
