import {useEffect,useState} from 'react';
import {api} from './api';
import {parseGrade} from '../supabase/functions/pokevault/grading';
import {ArrowUpRight,ShieldCheck} from 'lucide-react';
export default function GradingHelper({card,grading,language,onValue}:{card:any,grading:string,language:string,onValue:(value:string)=>void}){
 const [market,setMarket]=useState<any>(null),[loading,setLoading]=useState(false);
 const grade=parseGrade(grading),reference=grade?grade.referenceCompany+' '+grade.referenceGrade:grading;
 useEffect(()=>{let cancelled=false;setMarket(null);setLoading(true);api('?op=graded&lang='+encodeURIComponent(language)+'&id='+encodeURIComponent(card.id)+'&grading='+encodeURIComponent(grading)).then(r=>{if(!cancelled)setMarket(r);}).catch(()=>{if(!cancelled)setMarket({message:'Grading-Preis konnte nicht abgerufen werden.'});}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[card.id,language,grading]);
 const [sales,setSales]=useState('');const values=sales.split(/[;\n]/).map(s=>s.trim()).filter(Boolean).map(s=>Number(s.replace(',','.')));const valid=values.length>=3&&values.every(n=>Number.isFinite(n)&&n>0&&n<=1000000);const sorted=[...values].sort((a,b)=>a-b),median=valid?(sorted.length%2?sorted[Math.floor(sorted.length/2)]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2):null;
 const term=[card.name,card.set?.name,card.localId,language==='de'?'deutsch':language==='en'?'english':language,reference].filter(Boolean).join(' ');const link='https://www.ebay.de/sch/i.html?_nkw='+encodeURIComponent(term)+'&LH_Sold=1&LH_Complete=1';
 return <div className="grading-helper"><div className="grading-heading"><ShieldCheck size={18}/><strong>{grading} · Marktwert</strong></div><div className="graded-market" role="status">{loading?<p>Marktpreis wird abgefragt …</p>:market?.status==='available'?<><strong>{new Intl.NumberFormat('de-DE',{style:'currency',currency:market.currency}).format(market.price)}</strong>{market.priceEur!==null&&market.currency!=='EUR'&&<span>≈ {new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(market.priceEur)}</span>}<small>{market.source} · {market.sales} Verkäufe · Abruf {new Date(market.fetchedAt).toLocaleDateString('de-DE')}</small><small>{market.sourceUpdated?'Quellenstand: '+new Date(market.sourceUpdated).toLocaleDateString('de-DE'):'Die Quelle hat kein Aktualisierungsdatum geliefert.'}</small><small>{market.languageNote}</small>{market.comparison&&<p>AOG-Schätzung auf Basis von PSA 10.</p>}<small>Beim Speichern automatisch im Portfolio berücksichtigt, sofern ein Euro-Wert vorliegt. Ein eigener Wert hat Vorrang.</small></>:<><strong>Marktpreis noch nicht verfügbar</strong><p>{market?.message}</p><small>{reference}{grade?.comparison?' als AOG-Vergleichswert':''} · Fehlende Daten werden nicht geschätzt.</small></>}</div><a href={link} target="_blank" rel="noreferrer">Verkaufte Angebote bei eBay ansehen <ArrowUpRight size={15}/></a><details><summary>Wert aus eigenen Vergleichsverkäufen berechnen</summary><label>Mindestens 3 Verkaufspreise in €<textarea rows={2} value={sales} onChange={e=>setSales(e.target.value)} placeholder="z. B. 95; 110; 105"/></label><small>Mit Semikolon oder Zeilenumbruch trennen; Versandkosten herausrechnen. Der Median stammt aus deinen Eingaben, nicht aus einem automatischen eBay-Abruf.</small>{median!==null&&<div className="median-result"><strong>{new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(median)}</strong><span>Median aus {values.length} Verkäufen</span><button type="button" className="secondary" onClick={()=>onValue(median.toFixed(2))}>Als eigenen Wert übernehmen</button></div>}</details><small>Ohne verfügbaren Marktpreis oder eigenen Wert bleibt diese Karte im Portfolio unbewertet.</small></div>;
}
