'use client';
import {useState} from 'react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
export default function HistoryChart({history,scope,total,day,count,valued}:{history:any[],scope:string,total:number,day:string,count:number,valued:number}){
 const [range,setRange]=useState(30);
 const points=history.filter(x=>x.scope===scope).map(x=>({day:x.day,value:x.total_cents/100,count:x.card_count,valued:x.valued_count,failed:x.failed}));
 const live={day,value:total,count,valued,failed:points.find(p=>p.day===day)?.failed||0};const index=points.findIndex(p=>p.day===day);if(index>=0)points[index]=live;else points.push(live);points.sort((a,b)=>a.day.localeCompare(b.day));
 const cutoff=new Date(day+'T12:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-range+1);const shown=range?points.filter(p=>p.day>=cutoff.toISOString().slice(0,10)):points;
 const label=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'});
 return <section className="history-panel"><div className="history-heading"><div><h2>Portfolio-Verlauf</h2><p>Tagesstände deiner Sammlung</p></div><div className="range-control" aria-label="Zeitraum">{[[7,'7 Tage'],[30,'30 Tage'],[90,'90 Tage'],[0,'Gesamt']].map(([v,l])=><button key={v} className={range===v?'selected':''} onClick={()=>setRange(Number(v))}>{l}</button>)}</div></div><div className="history-value"><strong>{euro(total)}</strong><span>Aktueller erfasster Wert · {label(day)}</span></div><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={shown} margin={{top:12,right:14,bottom:10,left:0}}><defs><linearGradient id="portfolio-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--blue)" stopOpacity={.26}/><stop offset="100%" stopColor="var(--blue)" stopOpacity={.015}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="day" tickFormatter={label} tick={{fontSize:12,fill:'var(--muted)'}} tickLine={false} axisLine={false} minTickGap={30}/><YAxis width={70} tickFormatter={v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(v)+' €'} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false} domain={[0,'auto']}/><Tooltip content={({active,payload}:any)=>active&&payload?.length?<div className="chart-tooltip"><strong>{label(payload[0].payload.day)}</strong><span>{euro(payload[0].value)}</span><small>{payload[0].payload.valued} von {payload[0].payload.count} Karten bewertet</small>{payload[0].payload.failed>0&&<small>Teilweise mit bisherigen Preisen</small>}</div>:null}/><Area type="linear" dataKey="value" name="Sammlungswert" stroke="var(--blue)" strokeWidth={2.5} fill="url(#portfolio-fill)" dot={shown.length===1?{r:5,strokeWidth:2,fill:'var(--blue)'}:false} activeDot={{r:5}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><div className="history-caption"><span>{shown.length<2?'Weitere Tagesstände erscheinen nach der nächsten Aktualisierung.':'Täglich gespeicherte Sammlungswerte.'}</span><span>Käufe, Verkäufe und eigene Werte beeinflussen den Verlauf.</span></div></section>;
}
