import React,{useState,useEffect,Suspense,lazy} from 'react';
import {createRoot} from 'react-dom/client';
const Vault=lazy(()=>import('./vault')); 
import './styles.css';
import ThemeToggle from './theme';
import Recovery,{readRecovery} from './recovery';
const recoveryCredentials=readRecovery();
function App(){const [recover,setRecover]=useState(Boolean(recoveryCredentials)),[notice,setNotice]=useState('');const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState('');async function load(){let r=await fetch('/api/auth');if(r.status===401){const refresh=await fetch('/api/auth/refresh',{method:'POST'});if(refresh.ok)r=await fetch('/api/auth');}if(r.ok)setUser(await r.json());else if(r.status!==401)setError('Die Anmeldung ist noch nicht eingerichtet oder nicht erreichbar.');setLoading(false);}useEffect(()=>{load().catch(()=>{setError('Dienst nicht erreichbar.');setLoading(false);});},[]);
if(loading)return <div className="login-shell">Portal wird geladen …</div>;if(user&&!recover)return <Suspense fallback={<div className="login-shell">Sammlung wird geladen …</div>}><Vault role={user.role} username={user.username} onLogout={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null);setPassword('');}}/></Suspense>;return <div className="login-shell"><section className="login-box"><div className="login-theme"><span className="pokeball" aria-hidden="true"/><ThemeToggle/></div><div className="eyebrow">DEINE POKÉMON-SAMMLUNG</div><h1>PokéVault<span>.</span></h1><>{recover?<Recovery credentials={recoveryCredentials} onBack={()=>{setRecover(false);setError('');}} onDone={()=>{setUser(null);setRecover(false);setNotice('Dein Passwort wurde geändert. Melde dich mit deinem neuen Passwort an.');}}/>:<><p>Melde dich mit deinem Benutzerkonto an.</p>{notice&&<p className="message" role="status">{notice}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});if(!r.ok){const data:any=await r.json();throw Error(data.error||'Anmeldung fehlgeschlagen.');}setPassword('');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Benutzername<input required autoFocus autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Passwort<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="message error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Anmelden …':'Anmelden'}</button></form><button className="recovery-link" type="button" onClick={()=>{setRecover(true);setError('');setPassword('');}}>Passwort vergessen?</button><small>Jedes Konto hat seine eigene Sammlung.</small></>}</></section></div>;}
createRoot(document.getElementById('root')!).render(<App/>);
