import {useEffect,useRef,useState} from 'react';
import {api} from './api';
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
function ProductImage({product}:{product:any}){const [failed,setFailed]=useState(false);return failed?<div className="sealed-image-error">Produktbild derzeit nicht erreichbar<br/><a href={product.sourceUrl} target="_blank" rel="noreferrer">Produkt ansehen</a></div>:<img src={product.image} alt={product.name+' · deutsche Verpackung'} loading="lazy" decoding="async" onError={()=>setFailed(true)}/>;}
export default function SealedPanel({state,readOnly=false,initialCollection='all',onChanged=async()=>{}}:{state:any,readOnly?:boolean,initialCollection?:string,onChanged?:()=>Promise<any>}){
 const collections=(state.collections||[]).filter((c:any)=>c.kind==='sealed');
 const [collection,setCollection]=useState(collections.some((c:any)=>c.id===initialCollection)?initialCollection:'all'),[catalog,setCatalog]=useState<any[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[page,setPage]=useState(0),[browse,setBrowse]=useState(false),[newName,setNewName]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<any>(null),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>({});
 useEffect(()=>{setCollection(collections.some((c:any)=>c.id===initialCollection)?initialCollection:'all');},[initialCollection]);
 const [loadingCatalog,setLoadingCatalog]=useState(false),[catalogError,setCatalogError]=useState(''),[catalogAttempt,setCatalogAttempt]=useState(0);
 const modalRef=useRef<HTMLElement>(null),busyRef=useRef(false);busyRef.current=busy;
 useEffect(()=>{if(!browse||catalog.length)return;let cancelled=false;setLoadingCatalog(true);setCatalogError('');api('?op=sealed-catalog').then(data=>{if(!cancelled)setCatalog(data);}).catch(e=>{if(!cancelled)setCatalogError(e.message);}).finally(()=>{if(!cancelled)setLoadingCatalog(false);});return()=>{cancelled=true;};},[browse,catalogAttempt]);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement,body=document.body,scrollY=window.scrollY;const before={position:body.style.position,top:body.style.top,width:body.style.width,overflow:body.style.overflow};body.style.position='fixed';body.style.top=`-${scrollY}px`;body.style.width='100%';body.style.overflow='hidden';const dialog=modalRef.current;dialog?.focus();const key=(e:KeyboardEvent)=>{if(!dialog)return;if(e.key==='Escape'&&!busyRef.current){e.preventDefault();setSelected(null);}if(e.key==='Tab'){const nodes=Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]'));if(!nodes.length){e.preventDefault();return;}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||!nodes.includes(document.activeElement as HTMLElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!nodes.includes(document.activeElement as HTMLElement))){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);Object.assign(body.style,before);window.scrollTo(0,scrollY);if(previous?.isConnected)previous.focus({preventScroll:true});};},[selected]);
 const rows=(state.sealedItems||[]).filter((r:any)=>collection==='all'||r.collection_id===collection),count=rows.reduce((n:number,r:any)=>n+r.quantity,0),total=rows.reduce((n:number,r:any)=>n+(r.value_cents||0)*r.quantity,0);
 const filtered=catalog.filter(p=>(kind==='all'||p.kind===kind)&&p.name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase()));
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const create=async(e:any)=>{e.preventDefault();await act(async()=>{const r=await api('',{op:'collection',name:newName,kind:'sealed'});await onChanged();setCollection(r.id);setCreating(false);setNewName('');setNotice('Sealed-Sammlung angelegt.');});};
 const choose=(product:any,row?:any)=>{setSelected(product);setEdit(row||null);setForm({collectionId:row?.collection_id||(collection!=='all'?collection:collections[0]?.id||''),quantity:row?.quantity||1,cost:row?.cost_cents===null||row?.cost_cents===undefined?'':row.cost_cents/100,value:row?.value_cents===null||row?.value_cents===undefined?'':row.value_cents/100,condition:row?.condition||'Originalversiegelt',note:row?.note||''});setError('');};
 const field=(key:string)=>({value:form[key]??'',onChange:(e:any)=>setForm({...form,[key]:e.target.value})});
 const save=async(e:any)=>{e.preventDefault();await act(async()=>{await api('',{op:edit?'sealed-edit':'sealed-add',id:edit?.id,productId:selected.id,...form,quantity:Number(form.quantity)});await onChanged();setSelected(null);setNotice('Versiegeltes Produkt gespeichert.');});};
 return <section className="sealed-page"><div className="page-heading"><div><div className="eyebrow">SEALED · DEUTSCH</div><h1>{readOnly?'Versiegelte Produkte':'Meine versiegelten Produkte'}</h1><p>Booster, Displays, Top-Trainer-Boxen und Kollektionen. Getrennt von Einzelkarten.</p></div>{!readOnly&&<div className="button-row"><button className="secondary" onClick={()=>setCreating(v=>!v)}>Sealed-Sammlung anlegen</button><button className="primary" onClick={()=>setBrowse(v=>!v)}>{browse?'Sammlung anzeigen':'Produkt hinzufügen'}</button></div>}</div>{error&&<p className="message error" role="alert">{error}</p>}{notice&&<p role="status" className="message success">{notice}</p>}{creating&&!readOnly&&<form className="settings-card" onSubmit={create}><label>Name der neuen Sealed-Sammlung<input required maxLength={80} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="z. B. Deutsche Displays"/></label><p>Diese Sammlung nimmt ausschließlich versiegelte Produkte auf.</p><button className="primary" disabled={busy}>Sammlung anlegen</button></form>}
 <div className="stats"><div className="stat"><span>Versiegelte Produkte</span><strong>{count}</strong><small>{rows.length} Einträge · Deutsch</small></div><div className="stat"><span>Erfasster Sealed-Wert</span><strong>{euro(total)}</strong><small>{rows.filter((r:any)=>r.value_cents!==null).length} von {rows.length} Einträgen bewertet · eigene Werte</small></div></div><label>Sealed-Sammlung<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="all">Alle Sealed-Sammlungen</option>{collections.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 {browse&&!readOnly?<><div className="toolbar"><label>Produkte suchen<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Name, Set oder Produkt …"/></label><label>Produktart<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0);}}><option value="all">Alle Produktarten</option>{[...new Set(catalog.map(p=>p.kind))].sort().map(k=><option key={k}>{k}</option>)}</select></label></div>{loadingCatalog?<p role="status" aria-live="polite">Produktkatalog wird geladen …</p>:catalogError?<div className="message error" role="alert"><p>Der Produktkatalog konnte nicht geladen werden.</p><button className="secondary" onClick={()=>setCatalogAttempt(n=>n+1)}>Erneut versuchen</button></div>:<p>{filtered.length} deutsche Produkte mit Bildern · Katalogquelle: CrispyCards. Händlerkatalog, keine Garantie für sämtliche historischen Produkte. Bilder und Verpackungsvariante vor dem Hinzufügen vergleichen.</p>}{!loadingCatalog&&!catalogError&&!filtered.length&&<p className="empty">Keine Produkte gefunden. Versuche einen kürzeren Namen oder eine andere Produktart.</p>}{!collections.length&&<p className="message">Lege zuerst eine separate Sealed-Sammlung an.</p>}<div className="sealed-grid">{filtered.slice(page*24,page*24+24).map(p=><article className="settings-card sealed-product" key={p.id}><ProductImage product={p}/><small>{p.kind} · Deutsch</small><h3>{p.name}</h3><a href={p.sourceUrl} target="_blank" rel="noreferrer">Produktbeschreibung</a><button className="primary" disabled={!collections.length||busy} onClick={()=>choose(p)}>Zur Sealed-Sammlung hinzufügen</button></article>)}</div>{filtered.length>24&&<div className="catalog-pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Zurück</button><span>{page+1} / {Math.ceil(filtered.length/24)}</span><button className="secondary" disabled={(page+1)*24>=filtered.length} onClick={()=>setPage(p=>p+1)}>Weiter</button></div>}</>:<><div className="sealed-grid">{rows.map((r:any)=><article className="settings-card sealed-product" key={r.id}>{r.product?<><ProductImage product={r.product}/><small>{r.product.kind} · Deutsch · {collections.find((c:any)=>c.id===r.collection_id)?.name}</small><h3>{r.product.name}</h3></>:<h3>Produkt nicht im Katalog</h3>}<p>{r.quantity} × · {r.condition}</p><strong>{r.value_cents===null?'Wert offen':euro(r.value_cents*r.quantity)}</strong><small>{r.value_cents===null?'Für einen genauen Wert einen eigenen Preis eintragen.':'Eigener eingetragener Wert · kein automatischer Marktpreis'}</small>{!readOnly&&<button className="secondary" disabled={!r.product} onClick={()=>choose(r.product,r)}>Produkt bearbeiten</button>}</article>)}</div>{!rows.length&&<p className="empty">In dieser Sealed-Sammlung sind noch keine Produkte.</p>}</>}
 {selected&&!readOnly&&<div className="overlay top-overlay"><section ref={modalRef} tabIndex={-1} className="modal small-modal sealed-modal" role="dialog" aria-modal="true" aria-labelledby="sealed-title"><div className="modal-heading"><h2 id="sealed-title">{edit?'Produkt bearbeiten':'Produkt hinzufügen'}</h2><button className="icon-btn" type="button" disabled={busy} onClick={()=>setSelected(null)} aria-label="Schließen">×</button></div><div className="modal-scroll"><form onSubmit={save}><h3>{selected.name}</h3><p>Deutsch · {selected.kind}</p><label>Sealed-Sammlung<select required {...field('collectionId')}><option value="">Bitte wählen</option>{collections.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Anzahl<input type="number" required min="1" max="9999" step="1" {...field('quantity')}/></label><label>Verpackungszustand<select {...field('condition')}>{['Originalversiegelt','Folie beschädigt','Verpackung beschädigt'].map(v=><option key={v}>{v}</option>)}</select></label><div className="fields-two"><label>Einkauf pro Produkt (€)<input type="number" min="0" step="0.01" placeholder="Optional" {...field('cost')}/></label><label>Eigener Wert pro Produkt (€)<input type="number" min="0" step="0.01" placeholder="Optional" {...field('value')}/></label></div><p>Der eigene Wert wird als solcher gekennzeichnet. Es gibt keine zusätzlichen Preis-API-Abfragen für Sealed-Produkte. Einkauf und Notizen bleiben privat.</p><label>Notiz<textarea rows={2} maxLength={1000} {...field('note')}/></label>{error&&<p className="message error" role="alert">{error}</p>}<div className="modal-footer">{edit&&<button type="button" className="danger" disabled={busy} onClick={()=>{if(window.confirm('Dieses Produkt aus deiner Sammlung entfernen?'))act(async()=>{await api('',{op:'sealed-delete',id:edit.id});await onChanged();setSelected(null);});}}>Entfernen</button>}<button className="primary" disabled={busy}>{busy?'Speichern …':'Produkt speichern'}</button></div></form></div></section></div>}
 </section>;
}
